### ISSUE TITLE
Plugin doesn't create route53 records

### ISSUE THREAD

**Issue by mohammedalnuaimi** [williamsandonz/serverless-website-domain#4]
Hey there,
Glad I found this plugin, I'm trying to use it to create a route53 record then point it to the desired  Cloudfront distribution, but it doesn't create the records! 
I have followed the example thoroughly even adding the other plugins thinking that they must be in, however I couldn't get it to work
Do I miss something? 
See below part of the serverless that concerning the plugin
```
service: common

package:
  individually: false

plugins:
  -serverless-website-domain
  -serverless-certificate-creator
  -serverless-s3-sync
  -serverless-cloudfront-invalidate

custom:
  shared: ${file(../environments/${opt:stage}.yml), file(../environments/default.yml)}
  domainComponents: #Key not needed, just used as example.
    withWWW: www.${self:custom.shared.packagesAlias}
    withoutWWW: ${self:custom.shared.packagesAlias}
  websiteDomain:
    cloudfrontOutputKey: !GetAtt PackagesCloudFrontDistribution.DomainName
    domain: ${self:custom.shared.packagesAlias} #must be hostedZoneDomain or subdomain of it
    edgeLambda:
      redirect:
        basicAuthCredentials: false
        from: ${self:custom.shared.packagesAlias}
        to: http://www.${self:custom.shared.packagesAlias}
  s3Sync:
      - bucketName: ${self:custom.shared.showsPackagesBucket}
        localDir: ./dist
  customCertificate:
      certificateName: ${self:custom.shared.domainCertificateARN}
      hostedZoneNames: dodo.xxxx.com
      subjectAlternativeNames:
        - ${self:custom.shared.packagesAlias}
  cloudfrontOriginId: packages
  cloudfrontInvalidate:
    - distributionIdKey: !GetAtt PackagesCloudFrontDistribution.Id
      items:
        - "/index.html"

variablesResolutionMode: 20210219
``` 

Appreciate your assistance with this issue

Thanks
